import jsPDF from "jspdf"
import {
  COMPANY_INFO,
  BRAND_COLORS,
  CURRENCY_OPTIONS,
} from "./invoice-types"
import {
  PAYMENT_METHOD_LABELS,
  formatAmount,
  formatReceiptDate,
  type PaymentReceiptData,
} from "./payment-receipt-types"

export async function generatePaymentReceiptPDF(data: PaymentReceiptData): Promise<void> {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  })

  const { primary } = BRAND_COLORS
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 18
  const contentWidth = pageWidth - margin * 2

  const currencyLabel = CURRENCY_OPTIONS.find((c) => c.value === data.currency)?.label ?? data.currency

  let y = margin

  doc.setDrawColor(primary.r, primary.g, primary.b)
  doc.setLineWidth(0.7)
  doc.line(margin, y + 16, pageWidth - margin, y + 16)

  doc.setFont("helvetica", "bold")
  doc.setFontSize(18)
  doc.setTextColor(primary.r, primary.g, primary.b)
  doc.text(COMPANY_INFO.name, margin, y + 6)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  doc.setTextColor(90, 90, 90)
  doc.text(COMPANY_INFO.email, margin, y + 11)
  doc.text(COMPANY_INFO.phone, margin + 55, y + 11)
  doc.text(COMPANY_INFO.website, margin + 95, y + 11)

  doc.setFont("helvetica", "bold")
  doc.setFontSize(24)
  doc.setTextColor(primary.r, primary.g, primary.b)
  doc.text("PAYMENT RECEIPT", pageWidth - margin, y + 8, { align: "right" })

  y += 24

  doc.setFillColor(247, 248, 250)
  doc.roundedRect(margin, y, contentWidth, 28, 2, 2, "F")

  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.setTextColor(90, 90, 90)
  doc.text("Reference:", margin + 4, y + 8)
  doc.text("Payment Date:", margin + 4, y + 15)
  doc.text("Purpose:", margin + 4, y + 22)

  doc.setTextColor(35, 35, 35)
  doc.text(data.invoiceId || "-", margin + 35, y + 8)
  doc.text(formatReceiptDate(data.paymentDate), margin + 35, y + 15)
  doc.text(data.paymentReason || "-", margin + 35, y + 22)

  y += 38

  doc.setFont("helvetica", "bold")
  doc.setFontSize(11)
  doc.setTextColor(primary.r, primary.g, primary.b)
  doc.text("CLIENT DETAILS", margin, y)

  y += 6
  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.setTextColor(30, 30, 30)
  doc.text(data.clientName || "-", margin, y)
  y += 5
  if (data.clientEmail) {
    doc.text(`Email: ${data.clientEmail}`, margin, y)
    y += 5
  }
  if (data.clientPhone) {
    doc.text(`Phone: ${data.clientPhone}`, margin, y)
    y += 5
  }
  if (data.clientAddress) {
    const addressLines = doc.splitTextToSize(data.clientAddress, contentWidth)
    doc.text(addressLines, margin, y)
    y += addressLines.length * 4.5
  }

  y += 4
  doc.setDrawColor(220, 220, 220)
  doc.line(margin, y, pageWidth - margin, y)
  y += 8

  doc.setFont("helvetica", "bold")
  doc.setFontSize(11)
  doc.setTextColor(primary.r, primary.g, primary.b)
  doc.text("PAYMENT SUMMARY", margin, y)
  y += 7

  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.setTextColor(40, 40, 40)
  doc.text(`Amount (${currencyLabel})`, margin, y)
  doc.text(formatAmount(data.amount, data.currency), pageWidth - margin, y, { align: "right" })
  y += 4
  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.setTextColor(40, 40, 40)
  doc.text(`Payment Method: ${PAYMENT_METHOD_LABELS[data.paymentMethod]}`, margin, y)
  y += 8

  if (data.comment.trim()) {
    y += 8
    doc.setFont("helvetica", "bold")
    doc.setTextColor(primary.r, primary.g, primary.b)
    doc.text("Comment", margin, y)
    y += 5
    doc.setFont("helvetica", "normal")
    doc.setTextColor(40, 40, 40)
    const notesLines = doc.splitTextToSize(data.comment.trim(), contentWidth)
    doc.text(notesLines, margin, y)
  }

  const footerY = pageHeight - 14
  doc.setDrawColor(230, 230, 230)
  doc.line(margin, footerY - 6, pageWidth - margin, footerY - 6)
  doc.setFont("helvetica", "italic")
  doc.setFontSize(8.5)
  doc.setTextColor(110, 110, 110)
  doc.text("Thank you for your payment.", pageWidth / 2, footerY - 1, { align: "center" })
  doc.text("Generated by Jeexpert ERP Light", pageWidth / 2, footerY + 3.5, { align: "center" })

  const filename = data.invoiceId
    ? `payment-receipt-${data.invoiceId}.pdf`
    : "payment-receipt.pdf"
  doc.save(filename)
}
